name: Continuous Integration pipeline

on:
  pull_request:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Build package
        run: | 
          pnpm install
          pnpm build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
            name: package
            path: dist/
