name: CI/CD pipeline

on:
  push:
    branches:
      - lab11
  workflow_dispatch:
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
        working-directory: infra
      
      - name: Provision infrastructure
        uses: pulumi/actions@v4.2.1
        with:
          command: up
          stack-name: teachingiac/an-cb-vue-2048/dev
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
