name: CI/CD pipeline

on:
  push:
    branches:
      - lab11
  workflow_dispatch:
    
env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install
        working-directory: infra
      
      - name: Provision infrastructure
        uses: pulumi/actions@v4.2.1
        with:
          command: up
          stack-name: teachingiac/ei8it213/an-cb-vue-2048
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
